services:
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=todolistDB
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    depends_on:
      db:
        condition: service_healthy

    build: backend
    ports:
      - 8080:8080
    volumes:
      - ./backend/src:/app/src
    env_file:
      - ./global.env
      - ./backend/.env
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=todolistDB
      - DB_USER=postgres
      - DB_PASSWORD=postgres

  frontend:
    build: frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src:/app/src
    env_file:
      - ./global.env
